### ISSUE TITLE
Have you plans to add new weights?

### ISSUE THREAD

**Issue by cssobral2013** [impallari/Cabin#13]
Maybe... Light and/or ExtraLight?

**Comment by impallari** [comment]
We are extending it to a full family from thin to heavy

**Comment by Bronnel721** [comment]
@impallari, I'm not cssobral2013, but how's the process going?

**Comment by impallari** [comment]
https://raw.githubusercontent.com/impallari/AlphabetMagic/main/Experiment%2019%20-%20Make%20it%20Heavy/001%20-%20First%20Try/03%20-%20Control%20Result%20%20-%20Cabin%20Heavy%20Master%20by%20Node%20Dragging.jpg

**Comment by cssobral2013** [comment]
@impallari - So, could you please re-open this issue? Thank you!

**Comment by Bronnel721** [comment]
@impallari, can you send me the files to test them out?

**Comment by impallari** [comment]
Please wait... Will upload soon.
