### ISSUE TITLE
any plans to change the @ sign?

### ISSUE THREAD

**Issue by jazamora** [impallari/Cabin#15]
Looks like its part of a whole different font. Any plans on changing it?

**Comment by kevinyeong** [comment]
@jazamora I have Steven doing some quick research to see if we can swap it out. If not, we'll change.

**Comment by andronocean** [comment]
I'd like to see a more typical @ symbol, as well. The negative space design is jarring in form inputs. Happy to have the original glyph as an alternate!

**Comment by langermank** [comment]
> I'd like to see a more typical @ symbol, as well. The negative space design is jarring in form inputs. Happy to have the original glyph as an alternate!

You can access the alternate @ symbol by setting `font-feature-settings: "salt";` wherever you use the font. If you run the font in https://wakamaifondue.com/ you can see all the feature options 🙂
