### ISSUE TITLE
smcp feature?

### ISSUE THREAD

**Issue by rdtennent** [impallari/Cabin#18]
The sc glyphs are there but the smcp feature isn't enabled.

**Comment by davelab6** [comment]
In the font files, or in Google Fonts?

**Comment by rdtennent** [comment]
In the fonts at github.

**Comment by khaledhosny** [comment]
Checking the sources, both `smcp` and `c2sc` features has this line `disabled = 1;` which I guess is disabling them.

**Comment by rdtennent** [comment]
What program "compiles" the sources into fonts?

**Comment by rdtennent** [comment]
Khaled suggested I use fontmake and that worked okay.  But there were many warnings of the form

glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.O.sc found in kerning rules.

Are these significant? Why were small caps disabled?

**Comment by rdtennent** [comment]
Closed with no explanation.  There are still .sc glyphs in the version 3 fonts but no smcp feature.
