### ISSUE TITLE
Some weird issues prevent it to export as VF

### ISSUE THREAD

**Issue by impallari** [impallari/Cabin#4]
There are some really weird issues that prevent it to export as a VF
@kalapi What to have a look?

**Comment by kalapi** [comment]
@impallari Unfortunately I prefer not to run GlyphsApp's cutting edge versions, so I cannot test this yet.

**Comment by davelab6** [comment]
You can keep both by copying the .app bundle of stable and renaming it..?

**Comment by davelab6** [comment]
You can also try to generate VF with fontmake

**Comment by kalapi** [comment]
After fixing some inconsistencies, I was able to generate the variable fonts via GlyphsApp.

<img width="656" alt="screen shot 2016-11-17 at 12 12 05 pm" src="https://cloud.githubusercontent.com/assets/15804460/20378979/8e48855e-acbf-11e6-847e-47aaa00ffcf5.png">

However, with FontMake it breaks when trying to combine the GPOS tables. I use the following command:

```
fontmake -g <glyphsSource> -o variable
```

**Comment by davelab6** [comment]
Awesome, thanks @kalapi ! :) 

Regarding fontmake, cc @jamesgk

**Comment by jamesgk** [comment]
The fontmake issue is probably https://github.com/fonttools/fonttools/issues/719.
